---
steps:
- name: gcr.io/cloud-builders/gsutil
  args:
  - cp
  - gs://model_repo_de2022_group6/model.pkl
  - "./prediction-api"
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - "-t"
  - gcr.io/$PROJECT_ID/group6_prediction-api:0.0.1
  - "./prediction-api"
- name: gcr.io/cloud-builders/docker
  args:
  - push
  - gcr.io/$PROJECT_ID/group6_prediction-api:0.0.1
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
  - run
  - deploy
  - prediction-service-api-test
  - "--image"
  - gcr.io/$PROJECT_ID/group6_prediction-api:0.0.1
  - "--region"
  - us-central1
  - "--platform"
  - managed
  - "--allow-unauthenticated"
  - "--update-env-vars"
  - PROJECT_ID=$PROJECT_ID,MODEL_REPO=model_repo_de2022_group6,MODEL_NAME=model.pkl
  - "--no-cpu-throttling"
  - "--memory"
  - 4 Gi
